# Generated by Django 3.0.8 on 2020-07-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='inbox',
            field=models.TextField(max_length=3500),
        ),
    ]
