# Generated by Django 3.0.8 on 2020-07-10 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_story_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
